version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${PORT_FRONT}:${PORT_FRONT}"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: on-failure
    tty: true
    stdin_open: true
  
  db:
    image: mysql:8.2
    container_name: db
    ports:
      - ${PORT_DB}:${PORT_DB}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PORT_DB: ${PORT_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure