version: '3'
services:
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "${PORT_FRONT}:${PORT_FRONT}"
  #   depends_on:
  #     - backend
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    env_file:
      - ./backend/.env
    environment:
      HOST: db
    depends_on:
      - db
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - aprovados_bb

  db:
    image: postgres:latest
    container_name: db
    ports:
      - ${PORT_DB}:${PORT_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT_DB: ${PORT_DB}
    restart: on-failure
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    networks:
      - aprovados_bb

networks:
  aprovados_bb:
    driver: bridge