services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${PORT_FRONT}:${PORT_FRONT}"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: on-failure
    tty: true
    stdin_open: true
  
  db:
    build: ./database
    container_name: db
    ports:
      - "${PORT_DB}:${PORT_DB}"
    env_file:
      - ./database/.env
    volumes:
      - ./database/data:/var/lib/postgresql/data
    restart: on-failure