services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: on-failure
  
  db:
    build: ./database
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env
    volumes:
      - ./database/data:/var/lib/postgresql/data
    restart: on-failure