
export enum SiglasEstados{
  AC = 'AC',
  AL = 'AL', 
  AP = 'AP',
  AM = 'AM',
  BA = 'BA',
  CE = 'CE',
  DF = 'DF',
  ES = 'ES',
  GO = 'GO', 
  MA = 'MA',
  MT = 'MT',
  MS = 'MS',
  MG = 'MG',
  PA = 'PA',
  PB = 'PB',
  PR = 'PR',
  PE = 'PE', 
  PI = 'PI', 
  RJ = 'RJ',
  RN = 'RN',
  RS = 'RS',
  RO = 'RO',
  RR = 'RR',
  SC = 'SC',
  SP = 'SP',
  SE = 'SE',
  TO = 'TO' 
}



export const CertidaoNegativaFederal = 'https://www.cjf.jus.br/cjf/certidao-negativa';
export enum CertidaoNegativaEstadual{
  AC = 'http://esaj.tjac.jus.br/esaj/portal.do?servico=810000',
  AL = 'https://www2.tjal.jus.br/esaj/portal.do?servico=810100',
  AP = 'https://tucujuris.tjap.jus.br/tucujuris/pages/certidao-publica/certidao-publica.html',
  AM = 'https://consultasaj.tjam.jus.br/esaj/portal.do?servico=810100',
  BA = 'https://portalcertidoes.tjba.jus.br/#/primeirograu',
  CE = 'https://sirece.tjce.jus.br/sirece-web/nova/solicitacao.jsf',
  DF = 'https://cnc.tjdft.jus.br/',
  ES = 'http://www.tjes.jus.br/servicos/certidao-negativa-2/',
  GO = 'https://www.tjgo.jus.br/index.php/processos/emissao-de-certidoes',
  MA = 'https://jurisconsult.tjma.jus.br/#/certidao-generate-state-certificate-form',
  MT = 'https://sec.tjmt.jus.br/',
  MS = 'https://www5.tjms.jus.br/servicos/certidoes/',
  MG = 'https://www.tjmg.jus.br/portal-tjmg/processos/certidao-judicial/',
  PA = 'https://consultas.tjpa.jus.br/certidao/pages/pesquisaGeralCentralCertidao.action',
  PB = 'https://www.tjpb.jus.br/servicos/solicitar-certidao',
  //lembrar que nao emite online!!
  PR = 'https://www.tjpr.jus.br/certidoes/primeiro-grau',
  PE = 'https://www.tjpe.jus.br/web/processo-judicial-eletronico/pje-em-pernambuco/certidao',
  PI = 'https://www.tjpi.jus.br/themisconsulta/certidao',
  RJ = 'https://www4.tjrj.jus.br/Portal-Extrajudicial/certidao/judicial/solicitar',
  RN = 'https://apps.tjrn.jus.br/certidoes/f/public/index.xhtml',
  RS = 'https://www.tjrs.jus.br/novo/processos-e-servicos/servicos-processuais/emissao-de-antecedentes-e-certidoes/',
  RO = 'https://www.tjro.jus.br/certidao-unificada/certidaoPublicaEmitir',
  RR = 'http://certidao.tjrr.jus.br/certidao/pages/certidao/certidao-negativa',
  SC = 'https://certidoes.tjsc.jus.br/',
  SP = 'https://www.tjsp.jus.br/Certidoes/Certidoes/CertidoesPrimeiraInstancia',
  SE = 'https://www.tjse.jus.br/portal/servicos/judiciais/certidao-online/solicitacao-de-certidao-negativa',
  TO = 'https://www.tjto.jus.br/servicos/certidoes',
} 

export const FolhaAntecedentesFederal = 'https://www.gov.br/pf/pt-br/assuntos/antecedentes-criminais';
export enum FolhaAntecedentesEstadual{
  AC = '',
  AL = '',
  AP = '',
  AM = '',
  BA = '',
  CE = '',
  DF = '',
  ES = '',
  GO = '',
  MA = '',
  MT = '',
  MS = '',
  MG = '',
  PA = '',
  PB = '',
  PR = '',
  PE = '',
  PI = '',
  RJ = '',
  RN = '',
  RS = '',
  RO = '',
  RR = '',
  SC = '',
  SP = '',
  SE = '',
  TO = '',
}

