export { default as AprovadoRepo } from './AprovadoRepo'
export { default as CidadeRepo} from './CidadeRepo'
export { default as ContatoRepo } from './ContatoRepo'
export { default as DiretoriaRepo } from './DiretoriaRepo'
export { default as EstadoRepo } from './EstadoRepo'
export { default as LotacaoRepo } from './LotacaoRepo'
export { default as LotadoEmRepo } from './LotadoEmRepo'
export { default as RankingRepo } from './RankingRepo'
export { default as SituacaoRepo } from './SituacaoRepo'
export { default as TurmaRepo } from './TurmaRepo'
