// export { default as AprovadosRepository } from './AprovadoRepository';
// export { default as CidadeRepository } from './CidadeRepository';
// export { default as DiretoriaRepository } from './DiretoriaRepository';
// export { default as ListaRepository } from './ListaRepository';
// export { default as LotacaoRepository } from './LotacaoRepository';
// export { default as LotacaoEmRepository } from './LotadoEmRepository';
// export { default as SituacaoRepository } from './SituacaoRepository';
// export { default as TipoListaRepository } from './TipoListaRepository';
// export { default as TurmaRepository } from './TurmaRepository';
export { default as LoginRepository } from './LoginRepository';
export { default as UserRepository } from './UserRepository';
